### ISSUE TITLE
commands trigger error

### ISSUE THREAD

**Issue by IrealiTY** [IrealiTY/crc-bot#6]
```
0|discord  | 2017-01-31T00:29:49.568Z - debug: got message from [Saeris-Test] in channel [announcements]:  .iam casters
0|discord  | 2017-01-31T00:29:49.569Z - error:  TypeError: Cannot read property 'roles' of undefined
0|discord  |     at iam (/opt/bot/plugins/role.js:38:40)
0|discord  |     at next (native)
0|discord  |     at onFulfilled (/opt/bot/node_modules/co/index.js:65:19)
0|discord  |     at /opt/bot/node_modules/co/index.js:54:5
0|discord  |     at new wrappedPromise (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:372:16) 0|discord  |     at co (/opt/bot/node_modules/co/index.js:50:10)
0|discord  |     at Object.iam [as exec] (/opt/bot/plugins/role.js:27:12)
0|discord  |     at /opt/bot/bot.js:101:41
0|discord  |     at next (native)
0|discord  |     at onFulfilled (/opt/bot/node_modules/co/index.js:65:19)
```

**Comment by GeekyDeaks** [comment]
Ah - need a check to see if the defaultGuild is set before executing the command.  I'll add that to the test suite first...
